### PR TITLE
Da 611 adding title

### PR DESCRIPTION
**Pull request by mattbourke**
@lauriejones please review my pull

### CODE REVIEW

**Comment by lauriejones** [comment]
Looks pretty good. This is a new feature so should be a minor version change, also please update the readme with some doco about the new prop and the change log :+1:

**Comment by mattbourke** [comment]
@lauriejones please see the changes you requested

**Comment by lauriejones** [comment]
Thanks Matt. Could the name be changed from title to `prompt`? It's not really a title for the section and it is not displayed at all screen sizes.

Also could you update the readme to include the props like we do for more recent front-end packages?

**Comment by lauriejones** [comment]
Publish away!

**Pull request merged**
